"""Frågorna för burnout-testet, utbrutet till egen fil för att hålla huvudfilen kortare."""

QUESTIONS = [
    {
        "title": "Mental Health Status",
        "description": "How would you describe your mental health?",
        "type": "select",
        "options": ["Critical", "Needs Attention", "Healthy"],
        "key": "mental_health_status",
        "mapping": {"Critical": 0, "Needs Attention": 1, "Healthy": 2},
    },
    {
        "title": "Stress Level",
        "description": "What's your stress level been like in the last 14 days?",
        "type": "select",
        "options": ["High", "Moderate", "Low"],
        "key": "stress_level",
        "mapping": {"High": 0, "Moderate": 1, "Low": 2},
    },
    {
        "title": "Chronic Stress",
        "description": "Do you experience chronic stress?",
        "type": "radio",
        "options": ["No", "Yes"],
        "key": "chronic_stress",
    },
    {
        "title": "Sleep Quality",
        "description": "How would you rate your sleep quality (last 14 days)?",
        "type": "select",
        "options": ["Poor", "Average", "Good", "Excellent"],
        "key": "sleep_quality",
        "mapping": {"Poor": 0, "Average": 1, "Good": 2, "Excellent": 3},
    },
    {
        "title": "Sleep Hours",
        "description": "How many hours do you sleep per night?",
        "type": "slider",
        "min": 2.0,
        "max": 12.0,
        "step": 0.5,
        "key": "sleep_hours",
    },
    {
        "title": "Work Hours",
        "description": "How many hours do you work per week?",
        "type": "slider",
        "min": 0.0,
        "max": 85.0,
        "step": 1.0,
        "key": "work_hours_per_week",
    },
    {
        "title": "Screen Time",
        "description": "How many hours of screen time per day?",
        "type": "slider",
        "min": 0.0,
        "max": 18.0,
        "step": 1.0,
        "key": "screen_time_hours",
    },
    {
        "title": "Meditation",
        "description": "How many minutes do you meditate per day?",
        "type": "slider",
        "min": 0.0,
        "max": 240.0,
        "step": 5.0,
        "key": "meditation_minutes",
    },
    {
        "title": "Physical Activity",
        "description": "How many hours of physical activity per week?",
        "type": "slider",
        "min": 0.0,
        "max": 13.0,
        "step": 0.5,
        "key": "physical_activity_hours",
    },
]
